spring:
  datasource:
    url: jdbc:h2:mem:blogdb;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.sql: debug

kakao:
  rest-api-key: c7b3d4c354d87e9267f8e8e1c2bf252f
  base-url: https://dapi.kakao.com


